#INCLUDE "RWMAKE.CH"
#INCLUDE "PROTHEUS.CH"

/*ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัออออออออออออออปฑฑ
ฑฑบPrograma ณ FT100MNU บAutor  ณ Adriano L. de Souza บ Data ณ  18/02/2014  บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯออออออออออออออนฑฑ
ฑฑบDesc.   ณ Ponto de entrada utilizado para inclusใo de bot๕es na tela de บฑฑ
ฑฑบDesc.   ณ regras de neg๓cios.                                           บฑฑ
ฑฑฬออออออออออุอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso P11  ณ Uso especํfico Arcolor                                       บฑฑ
ฑฑศออออออออออฯอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑอฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿*/

User Function FT100MNU()

Local _aSavArea := GetArea()

If ExistBlock("RFATA014")
	Aadd(aRotina,{'Incluir Padrใo'				,'U_RFATA014()' , 0 , 3,0,NIL})
EndIf

//Inํcio - Trecho adicionado por Adriano Leonardo em 07/08/2014, para adi็ใo de botใo na tela de regras de neg๓cios
If ExistBlock("RFATE054")
	Aadd(aRotina,{'Manuten็ใo Produto/Grupo'	,'U_RFATE054()' , 0 , 3,0,NIL})
EndIf
//Final  - Trecho adicionado por Adriano Leonardo em 07/08/2014, para adi็ใo de botใo na tela de regras de neg๓cios

RestArea(_aSavArea)

Return()