#include "totvs.ch"
#include "fweventviewconsts.ch"
#include "colors.ch"
/*/{Protheus.doc} MA200BUT
@description Ponto de Entrada para inserção da alteração do apontamento de horas improdutivas
@author  Diego Rodrigues Pereira (ALLSS Soluções em Sistemas)
@since   21/07/2021
@version P12.1.25 - 1.00
@see https://allss.com.br
/*/

User Function MTA682MNU()


Aadd( aRotina, {"Alterar OP","U_RPCPE006", 0 , 4,0,.F.} )

Return()

